In [1]:
import random
import numpy as np
from deap import algorithms, base, creator, tools

#### Tekrarlanabilirlik için seed ayarlanır

In [2]:
SEED_VALUE = 32
random.seed(SEED_VALUE)
np.random.seed(SEED_VALUE)

## Hiperparametreler

In [3]:
# Simüle edilecek nesil sayısı
n_generation = 32

# Popülasyon boyutu (birey sayısı)
n_population = 32

# Her bireyin gen sayısı
n_genes = 16

# Seçilim turnuvasında rastgele seçilecek birey sayısı (k)
selectionTournamentSize = 3

# Birey bazlı mutasyon olasılığı
individualMutationProbability = 0.10

## DEAP

#### "Uygunluk" ve "Birey" sınıflarını tanımla, uygunluk sınıfını bireye ait bir değer olacak şekilde parametre geç

In [4]:
creator.create("Fitness", base.Fitness, weights=(1.0,))
creator.create("Individual", list, fitness=creator.Fitness)

In [5]:
## Toolbox'ımız
toolbox = base.Toolbox()

#### Gen, birey ve popülasyon oluşturmamızı sağlayacak fonksiyonları oluşturup birbirine bağlayalım.

In [6]:
# Her bir bireyin her bir genini oluşturacak fonksiyonu toolbox içinde tanımla
# (0/1, boolean)
toolbox.register("initializeGene", random.randint, 0, 1)

# Bireyleri oluşturacak fonksiyonu toolbox içinde tanımla
toolbox.register("initializeIndividual", tools.initRepeat, creator.Individual, toolbox.initializeGene, n=n_genes)

# Popülasyonu oluşturacak fonksiyonu toolbox içinde tanımla
toolbox.register("initializePopulation", tools.initRepeat, list, toolbox.initializeIndividual, n=n_population)

*initializePopulation* yoluyla bir popülasyon oluşturulurken, içinde bulunacak bireyler *initializeIndividual* çağrılarak oluşturulur; her birey oluşturulurken ona ait olacak her bir gen ise *initializeGene* çağrılarak tanımlanır.

#### Gen, birey ve popülasyon oluşturan toolbox fonksiyonlarımızı test edelim

In [7]:
print(
	"+ Örnek gen ",
	toolbox.initializeGene()
)
print(
	"\n+ Örnek birey ",
	np.array(toolbox.initializeIndividual())
)
print(
	"\n+ Örnek popülasyon (n=5)\n",
	np.array(toolbox.initializePopulation(n=5))
)

+ Örnek gen  0

+ Örnek birey  [0 0 1 0 1 0 0 0 1 1 0 1 1 0 0 0]

+ Örnek popülasyon (n=5)
 [[1 0 1 0 1 0 1 0 0 0 0 1 0 1 0 0]
 [1 0 0 1 1 1 0 1 0 0 1 0 1 1 0 0]
 [1 1 1 0 1 0 0 1 0 0 0 0 1 0 1 0]
 [1 0 0 0 1 0 1 1 1 1 0 1 0 0 1 1]
 [1 0 0 1 1 0 0 0 1 0 0 0 0 1 1 0]]


#### Uygunluk fonksiyonumuzu toolbox yoluyla tanımlayalım (gen değerlerinin toplamı)

In [8]:
toolbox.register("evaluate", lambda individual_genes: (sum(individual_genes), ))

#### Çaprazlama, mutasyon ve seçilimi uygulayacak fonksiyonlarımızı toolbox yoluyla tanımlayalım

In [9]:
# Çaprazlama metodu: Tek noktalı çaprazlama
toolbox.register("mate", tools.cxOnePoint)

# Mutasyon metodu: Bit flip mutasyonu
# ! indpb = %15 olasılık değeri burada her gen için belirlenir, birey için değil !
toolbox.register("mutate", tools.mutFlipBit, indpb=0.15)

# Seçilim metodu: Turnuva seçilimi, k = selectionTournamentSize
toolbox.register("select", tools.selTournament, tournsize=selectionTournamentSize)

#### Uygunluğu ölçen; çaprazlama, mutasyon ve seçilim operatörlerini uygulayacak toolbox fonksiyonlarımızı test edelim

In [10]:
# Test için iki birey tanımlayalım
ind1 = toolbox.initializeIndividual()
ind2 = toolbox.initializeIndividual()

In [11]:
print(
	"+ Uygunluk skoru\n",
	np.array(ind1), toolbox.evaluate(ind1),
	"\n",
	np.array(ind2), toolbox.evaluate(ind2)
)

+ Uygunluk skoru
 [1 1 0 1 1 0 1 1 0 0 0 1 1 1 1 0] (10,) 
 [0 0 0 0 0 1 1 0 0 1 1 0 0 0 1 0] (5,)


In [12]:
print(
	"+ Tek Noktalı Çaprazlama\n",
	np.array(ind1), "Birey 1\n",
	np.array(ind2), "Birey 2\n",
	"\nYeni bireyler\n",
	np.array(toolbox.mate(ind1, ind2))
)

+ Tek Noktalı Çaprazlama
 [1 1 0 1 1 0 1 1 0 0 0 1 1 1 1 0] Birey 1
 [0 0 0 0 0 1 1 0 0 1 1 0 0 0 1 0] Birey 2
 
Yeni bireyler
 [[1 1 0 1 1 0 1 1 0 1 1 0 0 0 1 0]
 [0 0 0 0 0 1 1 0 0 0 0 1 1 1 1 0]]


In [13]:
print(
	"+ Bit Flip Mutasyonu\n",
	np.array(ind1), "Birey\n",
	np.array(toolbox.mutate(ind1)[0]), "Mutasyon uygulanmış hali",
)

+ Bit Flip Mutasyonu
 [1 1 0 1 1 0 1 1 0 1 1 0 0 0 1 0] Birey
 [1 0 0 1 0 1 1 1 1 1 1 0 0 0 1 0] Mutasyon uygulanmış hali


In [14]:
print("+ Turnuva Seçilimi (parent selection) (k=2)")

# Örnek popülasyon tanımla
examplePopulation = toolbox.initializePopulation(n=6)

# Bireylerin uygunluklarını hesaplayıp üstlerine yaz (seçilim operatörü bu değeri okuyarak seçiyor)
fitnesses = [toolbox.evaluate(ind) for ind in examplePopulation]
for ind, fitnessScore in zip(examplePopulation, fitnesses):
	ind.fitness.values = fitnessScore

# Popülasyonu uygunluk skorlarıyla yazdır
for ind in examplePopulation:
	print(np.array(ind), ind.fitness.values[0])

# Seçilim operatörünü uygula
# tournsize, daha önce gösterdiğimiz k parametresi, yani uygunluğa bakılmadan kaç birey seçilip aralarında turnuva yapılacağını belirler
# Burada geçen k parametresi ise turnuvanın kaç defa gerçekleşeceği
selectedInd = toolbox.select(examplePopulation, k=1, tournsize=2)[0]
print("Seçilen birey: ", selectedInd, toolbox.evaluate(selectedInd)[0])

+ Turnuva Seçilimi (parent selection) (k=2)
[0 0 0 0 0 0 1 1 1 0 0 1 0 0 0 0] 4.0
[0 0 0 1 1 0 0 1 1 0 0 1 0 1 0 0] 6.0
[1 1 1 0 0 1 1 0 0 1 1 0 1 1 1 0] 10.0
[0 1 0 0 0 0 1 0 0 0 0 1 0 1 1 1] 6.0
[1 1 0 1 1 1 0 1 1 0 1 1 0 0 0 1] 10.0
[0 1 1 0 0 1 1 1 0 0 1 1 0 0 0 1] 8.0
Seçilen birey:  [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1] 6


## Simülasyonu çalıştırma zamanı!

In [15]:
# Başlangıç popülasyonunu oluştur
initialPopulation = toolbox.initializePopulation(n=n_population)

# Simülasyon boyunca en uygun bireyin kaydını tutacak objemiz
hallOfFame = tools.HallOfFame(1)

# Fitness istatistiklerini tutacak objemiz
stats = tools.Statistics(lambda ind: ind.fitness.values[0])
stats.register("min", np.min)
stats.register("max", np.max)

# Simülasyon başlasın!
finalPopulation, logs = algorithms.eaSimple(
	population=initialPopulation,
	toolbox=toolbox,
	halloffame=hallOfFame,
	stats=stats,
	ngen=n_generation,
	cxpb=1,
	mutpb=individualMutationProbability,
	verbose=True
)

gen	nevals	min	max
0  	32    	2  	11 
1  	32    	6  	12 
2  	32    	7  	13 
3  	32    	9  	14 
4  	32    	10 	14 
5  	32    	9  	14 
6  	32    	10 	15 
7  	32    	13 	15 
8  	32    	13 	16 
9  	32    	11 	16 
10 	32    	12 	16 
11 	32    	14 	16 
12 	32    	14 	16 
13 	32    	16 	16 
14 	32    	14 	16 
15 	32    	11 	16 
16 	32    	14 	16 
17 	32    	14 	16 
18 	32    	14 	16 
19 	32    	13 	16 
20 	32    	13 	16 
21 	32    	12 	16 
22 	32    	14 	16 
23 	32    	13 	16 
24 	32    	13 	16 
25 	32    	13 	16 
26 	32    	12 	16 
27 	32    	13 	16 
28 	32    	13 	16 
29 	32    	13 	16 
30 	32    	13 	16 
31 	32    	16 	16 
32 	32    	16 	16 


##### Gen sayısı çok küçük olduğu için optimal sonucun bulunması hiç zor olmadı doğal olarak :)

In [16]:
bestIndividual = hallOfFame[0]
print("[+] En iyi uygunluk sağlayan bireyin skoru: {}".format(bestIndividual.fitness.values[0]))
print("Genotipi: ", bestIndividual)

[+] En iyi uygunluk sağlayan bireyin skoru: 16.0
Genotipi:  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
